#只启动bigdata-container:
#docker compose build bigdata-container
#docker compose up bigdata-container

networks:
  bigdata-net-1:
    driver: bridge
    ipam:
      config:
        - subnet: 172.19.0.0/16

services:
  bigdata-container:
    container_name: bigdata-container
    build: .
    image: bigdata-docker:v1.0
    networks:
      - bigdata-net-1
    ports:
      - "0.0.0.0:2181:2181"
      - "0.0.0.0:2222:22"
      - "0.0.0.0:3307:3306"
      - "0.0.0.0:7077:7077"
      - "0.0.0.0:8040:8040"
      - "0.0.0.0:8042:8042"
      - "0.0.0.0:8080:8080"
      - "0.0.0.0:8081:8081"
      - "0.0.0.0:8082:8082"
      - "0.0.0.0:8083:8083"
      - "0.0.0.0:8085:8085"
      - "0.0.0.0:8088:8088"
      - "0.0.0.0:9090:9090"
      - "0.0.0.0:9092:9092"
      - "0.0.0.0:9095:9095"
      - "0.0.0.0:8765:8765"
      - "0.0.0.0:9870:9870"
      - "0.0.0.0:10000:10000"
      - "0.0.0.0:16010:16010"
      - "0.0.0.0:16030:16030"
      - "0.0.0.0:41414:41414"

  jupyter:
    container_name: jupyter
    build:
      context: .
      dockerfile: Jupyter.Dockerfile
    image: jupyter:v1.0
    networks:
      - bigdata-net-1
    ports:
      - "0.0.0.0:8888:8888"